name: New Release

on:
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set release tag (yy.MM.dd)
              id: set_tag
              run: echo "TAG=$(date +'%y.%m.%d')" >> $GITHUB_OUTPUT

            - name: Compress windows and windows-update directories
              run: |
                    zip -r release.zip windows windows-update

            - name: Create Git tag
              run: |
                    git config user.name "github-actions[bot]"
                    git config user.email "github-actions[bot]@users.noreply.github.com"
                    git tag ${{ steps.set_tag.outputs.TAG }}
                    git push origin ${{ steps.set_tag.outputs.TAG }}

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                    tag_name: ${{ steps.set_tag.outputs.TAG }}
                    name: Release ${{ steps.set_tag.outputs.TAG }}
                    files: release.zip
              env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
